
pull:
	sudo docker pull mcr.microsoft.com/mssql/server:2022-latest

up:
	sudo docker-compose up -d

down:
	sudo docker-compose down

ps:
	sudo docker-compose ps

login:
	sudo docker-compose exec mssql bash

logs:
	sudo docker-compose logs
