
up:
	sudo docker compose up

upd:
	sudo docker compose up -d

build:
	sudo docker compose up --build

buildd:
	sudo docker compose up --build -d

down:
	sudo docker compose down

ps:
	sudo docker compose ps

login:
	sudo docker compose exec uzbox sh

clean:
	sudo rm -f ~/.docker/config.json 
