
pull:
	sudo docker pull postgres:12.19-bullseye

up:
	sudo docker-compose up -d

down:
	sudo docker-compose down

ps:
	sudo docker-compose ps

login:
	sudo docker-compose exec postgres bash

logs:
	sudo docker-compose logs
